### ISSUE TITLE
Linux VM Build TODO

### ISSUE THREAD

**Issue by pyrodie18** [kirk-bond/ACSC-2018#134]
- [ ] Run Yum Update
- [ ] Update Linux6 with correct flag
- [ ] Create bury flag for Linux7
- [ ] Create false flag for Linux7
- [ ] Create User Account
- [ ] Generate ssh key and ensure it works for User account
- [ ] Disable history for User account
- [ ] Change permissions on PS so user can't use it.
